config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :items
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'items#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  def self.categories = %w[vase glassware wall-art tableware other]
  validates :category, :inclusion => categories
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.where(user_id: current_user.id)
    @pagy, @items = pagy(@items, items: 10)

    @items = @items.sort_by { |item| [item.category, item.name] }


    @profit = 0
    @items.each do |item|
      @profit += (item.sellPrice - item.buyPrice)
    end
  end

  # GET /items/1 or /items/1.json
  def show
    if @item.user_id != current_user.id
      redirect_to items_path, alert: 'You are not authorized to view this item.'
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item)
            .permit(:name, :buyPrice, :sellPrice, :shipPrice,
                    :packed, :shipped, :buyer, :username,
                    :category, :buyDate, :sellDate)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, class: "contents") do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item-container">
    <div class="m-3 d-flex flex-column">
      <%= form.label :name %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :category, 'Category' %>
      <%= form.select :category, 
        options_for_select(Item.categories, @item.category) %>
      </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :buyPrice, 'Buy Price' %>
      <%= form.text_field :buyPrice, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :sellPrice, 'Sell Price' %>
      <%= form.text_field :sellPrice, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :shipPrice, 'Shipping Cost' %>
      <%= form.text_field :shipPrice, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :buyer %>
      <%= form.text_field :buyer, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3 d-flex flex-column">
      <%= form.label :username %>
      <%= form.text_field :username, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    
    <div class="m-3 d-flex flex-column">
      <%= form.label :buyDate, 'Buy Date' %>
      <%= form.date_field :buyDate, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    
    <div class="m-3 d-flex flex-column">
      <%= form.label :sellDate, 'Sell Date' %>
      <%= form.date_field :sellDate, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="m-3">
      <%= form.label :packed %>
      <%= form.check_box :packed, class: "block mt-2 h-5 w-5" %>
    </div>

    <div class="m-3">
      <%= form.label :shipped %>
      <%= form.check_box :shipped, class: "block mt-2 h-5 w-5" %>
    </div>
  </div>
  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="item-container">
  <p class="">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= item.name %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= item.category %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Buy Price:</strong>
    <%= number_to_currency(item.buyPrice) %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Sell Price:</strong>
    <%= number_to_currency(item.sellPrice) %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Profit:</strong>
    <%= number_to_currency(item.sellPrice - item.buyPrice) %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Ship Price:</strong>
    <%= number_to_currency(item.shipPrice) %>
  </p>

  <div>
    <strong class="block font-medium mb-1">Packed:</strong>
    <%= check_box_tag 'shipped', 'item shipped', item.packed, class: "form-check-input", disabled: true %>
  </div>

  <div>
    <strong class="block font-medium mb-1">Shipped:</strong>
    <%= check_box_tag 'shipped', 'item shipped', item.shipped, class: "form-check-input", disabled: true %>
  </div>

  <p class="">
    <strong class="block font-medium mb-1">Buyer:</strong>
    <%= item.buyer %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Username:</strong>
    <%= item.username %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Buy Date:</strong>
    <%= item.buyDate %>
  </p>

  <p class="">
    <strong class="block font-medium mb-1">Sell Date:</strong>
    <%= item.sellDate %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this item", item, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this item', edit_item_path(item), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing item</h1>

  <%= render "form", item: @item %>

  <%= link_to "Back to items", items_path, class: "btn btn-primary mt-3"  %>
</div>

app/views/items/index.html.erb
<div class="w-full">
  <div class="d-flex justify-between items-center">
    <div>
      <h1 class="font-bold text-4xl flex-grow-1">Inventory</h1>
      <%= link_to 'New item', new_item_path, class: "btn btn-secondary" %>
    </div>
    <h2 class="font-bold text-2xl mt-1 ms-auto">Total Profit: <%= @profit %></h2>
  </div>

  <div id="items" class="min-w-full mt-4">
    <% @items.each do |item| %>
      <%= link_to item.name, item, class: "rounded-lg py-3 px-5 btn btn-primary font-medium mb-3" %>
    <% end %>
  </div>
</div>

<%== pagy_nav(@pagy) %>

app/views/items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New item</h1>

  <%= render "form", item: @item %>

  <%= link_to 'Back to items', items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @item %>

    <div class="d-flex flex-row">
      <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-primary" %>
      <%= button_to 'Delete', item_path(@item), method: :delete, class: "btn btn-danger text-white mx-2" %>
      <%= link_to 'Back', items_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>